local disabled = {
  "NStefan002/screenkey.nvim",
  config = function()
    require("screenkey").setup({
      win_opts = {
        row = 1, --vim.o.lines - vim.o.cmdheight - 4,
        col = vim.o.columns - 1,
        relative = "editor",
        anchor = "NE",
        width = 30,
        height = 2,
        border = "none",
        title = "",
        title_pos = "center",
        style = "minimal",
        focusable = false,
        noautocmd = true,
      },
      hl_groups = {
        ["screenkey.hl.key"] = { link = "Normal" },
        ["screenkey.hl.map"] = { link = "Normal" },
        ["screenkey.hl.sep"] = { link = "Normal" },
      },
      winblend = 1,
      compress_after = 3,
      clear_after = 2,
      emit_events = true,
      disable = {
        filetypes = {},
        buftypes = {},
        modes = {},
      },
      show_leader = true,
      group_mappings = true,
      display_infront = {},
      display_behind = {},
      filter = function(keys)
        return keys
      end,
      colorize = function(keys)
        return keys
      end,
      separator = " ",
      keys = {
        ["<TAB>"] = "󰌒",
        ["<CR>"] = "󰌑",
        ["<ESC>"] = "Esc",
        ["<SPACE>"] = "␣",
        ["<BS>"] = "󰌥",
        ["<DEL>"] = "Del",
        ["<LEFT>"] = "",
        ["<RIGHT>"] = "",
        ["<UP>"] = "",
        ["<DOWN>"] = "",
        ["<HOME>"] = "Home",
        ["<END>"] = "End",
        ["<PAGEUP>"] = "PgUp",
        ["<PAGEDOWN>"] = "PgDn",
        ["<INSERT>"] = "Ins",
        ["<F1>"] = "󱊫",
        ["<F2>"] = "󱊬",
        ["<F3>"] = "󱊭",
        ["<F4>"] = "󱊮",
        ["<F5>"] = "󱊯",
        ["<F6>"] = "󱊰",
        ["<F7>"] = "󱊱",
        ["<F8>"] = "󱊲",
        ["<F9>"] = "󱊳",
        ["<F10>"] = "󱊴",
        ["<F11>"] = "󱊵",
        ["<F12>"] = "󱊶",
        ["CTRL"] = "Ctrl",
        ["ALT"] = "Alt",
        ["SUPER"] = "󰘳",
        ["<leader>"] = "_",
      },
      notify_method = "echo",
      log = {
        min_level = vim.log.levels.OFF,
        filepath = vim.fn.stdpath("data") .. "/screenkey_log",
      },
    })
    vim.cmd("Screenkey")
  end,
}
return {}
